# NumPy（Numerical Python）

### 数据维度的Python表示
- 一维数据：列表和集合类型
- 二维数据：列表类型
- 多维数据：列表类型
- 高维数据：字典类型或数据表示格式（JSON / XML / YAML等）

## 简介

NumPy是一个开源的Python科学计算基础库，包含：
- 一个强大的n维数组对象 ndarray
- 广播功能函数
- 整合 C/C++/Fortran 代码的工具
- 线性代数、傅里叶变换、随机数生成等功能

NumPy是SciPy、Pandas等数据处理或科学计算库的基础。

## 引用

In [3]:
import numpy as np

## n维数组对象 ndarray

#### Python已有列表类型，为何还需要一个数组对象类型？

- 数组对象可以去掉元素间运算所需的循环，使一维向量更像单个数据。
- 设置专门的数组对象，经过优化，可以提升这类应用的运算速度。
- 数组对象采用相同的数据类型，有助于节省运算和存储空间。

In [5]:
# 举例：计算 A² + B²，A和B是一维数组。

# 不用numpy
def pySum():
    a = [0, 1, 2, 3, 4]
    b = [9, 8, 7, 6, 5]
    c = []
    
    for i in range(len(a)):
        c.append(a[i]**2 + b[i]**2)
    return c
print(pySum())

[81, 65, 53, 45, 41]


In [7]:
# 使用numpy
import numpy as np

def npSum():
    a = np.array([0, 1, 2, 3, 4])
    b = np.array([9, 8, 7, 6, 5])
    
    c = a**2 + b**2
    return c

print(npSum())

[81 65 53 45 41]


### ndarry简介

ndarray是一个多维数组对象，由两部分构成：
- 实际的数据
- 描述这些数据的元数据（数据维度、数据类型等）

ndarray数组一般要求所有元素类型相同，数组下标从 0 开始。

`np.array()` 生成一个ndarray数组。

In [11]:
a = np.array([[0, 1, 2, 3, 4],
              [9, 8, 7, 6, 5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

`np.array()` 输出成`[]`形式，元素用空格分隔。

In [10]:
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


- axis（轴）：保存数据的维度
- rank（秩）：轴的数量

### ndarray对象的属性

|属性|说明|
|---|---|
|.ndim|秩，即轴的数量或维度的数量|
|.shape|ndarray对象的尺度，n行m列|
|.size|ndarray对象元素的个数，相当于.shape中n*m的值|
|.dtype|ndarray对象的元素类型|
|.itemsize|ndarray对象中每个元素的大小，以字节为单位|

### ndarray的元素类型

|数据类型|说明|
|---|---|
|bool|布尔类型，True或False|
|intc|与c语言中int类型一致，一般是int32或int64|
|intp|用于索引的整数，与c语言中ssize_t一致，int32或int64|
|int8|字节长度的整数，取值：[-128, 127]|
|int16|16位长度的整数，取值：[-32768, 32767]|
|int32|32位长度的整数，取值：[-2^31, 2^31-1]|
|int64|64位长度的整数，取值：[-2^63, 2^63-1]|
|uint8|8位无符号整数，|
|uint16||
|uint32||
|uint64||
|float16||
|float32||
|float64||
|complex64||
|complex128||


### ndarray数组的创建方法

#### 从Python中的列表、元组等类型创建ndarray数组

In [14]:
# x = np.array(list/tuple, dtype=np.float32)
# 当np.array()不指定dtype时，NumPy将根据数据情况关联一个dtype类型。

In [18]:
# 列表类型
x = np.array([0, 1, 2, 3])
print(x)

[0 1 2 3]


In [17]:
# 元组类型
x = np.array((4, 5, 6, 7))
print(x)

[4 5 6 7]


In [19]:
# 列表和元组混合类型
x = np.array([[1,2], [9, 8], (0.1, 0.2)])
print(x)

[[1.  2. ]
 [9.  8. ]
 [0.1 0.2]]


#### 使用NumPy中函数创建ndarray数组

|函数|说明|
|---|---|
|np.arange(n)||
|np.ones(shape)||
|np.zeros(shape)||
|np.full(shape, val)||
|np.eye(n)||
|np.ones_like(a)||
|np.zeros_like(a)||
|np.full_like(a,val)||
|np.linspace()||
|np.concatenate()||